# Generated by Django 4.2.4 on 2023-08-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99, verbose_name='نام دسته بندی')),
                ('image', models.ImageField(upload_to='', verbose_name='عکس دسته بندی')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=199, verbose_name='نام تحویل گیرنده')),
                ('receiver_address', models.TextField(verbose_name='ادرس تحویل گیرنده')),
                ('receiver_phone', models.CharField(max_length=11, verbose_name='شماره تحویل گیرنده')),
                ('order_full_price', models.PositiveBigIntegerField(verbose_name='قیمت کل سفارش')),
                ('order_date', models.DateField(auto_now=True, verbose_name='تاریخ سفارش')),
                ('order_delivery_date', models.DateTimeField(verbose_name='تاریخ تحویل سفارش')),
                ('status', models.CharField(choices=[('1', 'سبد خرید'), ('2', 'در انتظار پرداخت'), ('3', 'در انتظار تایید'), ('4', 'در حال ارسال'), ('5', 'تحویل شد'), ('6', 'انصراف داده شد')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99, verbose_name='نام محصول')),
                ('image', models.ImageField(upload_to='', verbose_name='عکس محصول')),
                ('description', models.TextField(verbose_name='توضیحات محصول')),
                ('stock', models.PositiveIntegerField(verbose_name='موجودی محصول')),
                ('price', models.PositiveBigIntegerField(verbose_name='قیمت محصول')),
                ('discount', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='تخفیف محصول')),
                ('special', models.BooleanField(verbose_name='ویژه')),
            ],
        ),
    ]
