# Generated by Django 4.2.4 on 2023-08-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارشات'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصول ها'},
        ),
        migrations.AddField(
            model_name='product',
            name='selled_count',
            field=models.IntegerField(default=0, verbose_name='تعداد فروش'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'سبد خرید'), ('2', 'در انتظار پرداخت'), ('3', 'در انتظار تایید'), ('4', 'در حال ارسال'), ('5', 'تحویل شد'), ('6', 'انصراف داده شد')], max_length=1, verbose_name='وضعیت'),
        ),
    ]
