# Generated by Django 4.1.2 on 2023-09-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_price', models.PositiveBigIntegerField(verbose_name='قیمت محصول')),
                ('product_discount', models.PositiveBigIntegerField(default=0, verbose_name='تخفیف محصول')),
                ('product_count', models.IntegerField(verbose_name='تعداد محصول')),
            ],
            options={
                'verbose_name': 'ایتم',
                'verbose_name_plural': 'ایتم ها',
            },
        ),
    ]
