# Generated by Django 4.2.5 on 2023-10-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_category_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('1', 'پرداخت انلاین'), ('2', 'پرداخت حضوری در فروشگاه'), ('3', 'پرداخت حضوری در منزل')], default='1', max_length=1, verbose_name='روش پرداخت'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_delivery_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تحویل سفارش'),
        ),
    ]
