# Generated by Django 4.2.5 on 2023-10-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_payment_method_alter_order_order_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('1', 'پرداخت انلاین'), ('2', 'پرداخت حضوری در فروشگاه'), ('3', 'پرداخت حضوری در منزل')], max_length=1, null=True, verbose_name='روش پرداخت'),
        ),
    ]
